/*
EI BASE DE DATOS I 5°B
    PROFESORA MTRA.SANDRA ELIZABETH LEON SOSA
EQUIPO:5 

INTEGRANTES: 
    CHAVEZ ROMERO MIGUEL            (CRMO15)     
    MARTINEZ CASTELLANOS EDUARDO    (MCEO161237)  
   
DESCRIPCION DE CLASE:
    Crear el fondo de los frames
 */
package imagenes;

import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author Julian
 */
public class NewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public NewJPanel() {
        initComponents();
        this.setSize(1920, 1080);
    }

    @Override
    protected void paintComponent(Graphics g) {
        Dimension tam=getSize();
        ImageIcon img=new ImageIcon(getClass().getResource("textura.jpg"));//Se obtiene el recurso en imagen
        g.drawImage(img.getImage(), 0, 0,tam.width,tam.height, this);
        setOpaque(false);
        super.paintComponent(g); //To change body of generated methods, choose Tools | Templates.
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1178, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 586, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
